name: Doxygen GitHub Pages Deploy Action
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install doxygen-awesome-css
        run: npm install https://github.com/jothepro/doxygen-awesome-css#v2.3.3 --save-dev
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
          config_file: Doxyfile
